name: Build

on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_IMAGE_PREFIX: ${{ secrets.DOCKER_IMAGE_PREFIX }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Download sapmachine JDK 17
        run: |
          download_url="https://github.com/SAP/SapMachine/releases/download/sapmachine-17.0.2/sapmachine-jdk-17.0.2_linux-x64_bin.tar.gz"
          wget -O "${RUNNER_TEMP}/sapmachine-jdk-17.tar.gz" "${download_url}"
      - name: Setup sapmachine JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'jdkfile'
          jdkFile: ${{ runner.temp }}/sapmachine-jdk-17.tar.gz
          java-version: '17.0.2'
          architecture: x64
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: amd64,arm64
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true
      - name: Set Multi-Builder Docker Buildx
        run: docker buildx create --use --name multi-builder --platform linux/arm64,linux/amd64
      - name: Maven Build and Analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
        run: mvn clean install
      - name: Docker Login
        run: docker login -u ${{secrets.DOCKER_USER}} -p ${{secrets.DOCKER_PASSWORD}} ${{secrets.DOCKER_REGISTRY}}
      - name: Push Kronos
        run: |
          cd releng/server
          cp -r "${JAVA_HOME}" jdk
          docker build --load -t ${DOCKER_IMAGE_PREFIX:-ghcr.io/codbex/}kronos --build-arg JDK_TYPE=external-jdk --build-arg JDK_HOME=jdk .
          docker push ${DOCKER_IMAGE_PREFIX:-ghcr.io/codbex/}kronos
          cd ../../
      - name: Push Kronos for SAP Cloud Foundry
        run: |
          cd releng/sap-cf
          cp -r "${JAVA_HOME}" jdk
          docker build --load -t ${DOCKER_IMAGE_PREFIX:-ghcr.io/codbex/}kronos-cf --build-arg JDK_TYPE=external-jdk --build-arg JDK_HOME=jdk .
          docker push ${DOCKER_IMAGE_PREFIX:-ghcr.io/codbex/}kronos-cf
          cd ../../
      - name: Push Kronos for SAP Kyma
        run: |
          cd releng/sap-kyma
          cp -r "${JAVA_HOME}" jdk
          docker build --load -t ${DOCKER_IMAGE_PREFIX:-ghcr.io/codbex/}kronos-kyma --build-arg JDK_TYPE=external-jdk --build-arg JDK_HOME=jdk .
          docker push ${DOCKER_IMAGE_PREFIX:-ghcr.io/codbex/}kronos-kyma
          cd ../../
      - name: Push Kronos for SAP Kyma Runtime
        run: |
          cd releng/sap-kyma-runtime
          docker build --load -t ${DOCKER_IMAGE_PREFIX:-ghcr.io/codbex/}kronos-kyma-runtime-base -f Dockerfile-base .
          docker push ${DOCKER_IMAGE_PREFIX:-ghcr.io/codbex/}kronos-kyma-runtime-base
          docker build --load -t ${DOCKER_IMAGE_PREFIX:-ghcr.io/codbex/}kronos-kyma-runtime .
          docker push ${DOCKER_IMAGE_PREFIX:-ghcr.io/codbex/}kronos-kyma-runtime
          docker build --load -t ${DOCKER_IMAGE_PREFIX:-ghcr.io/codbex/}kronos-kyma-runtime-distro -f Dockerfile-distro .
          docker push ${DOCKER_IMAGE_PREFIX:-ghcr.io/codbex/}kronos-kyma-runtime-distro
          cd ../../
      # - uses: buildpacks/github-actions/setup-pack@v4.1.0
      # - name: Kronos Buildpack
      #   run: |
      #     cd releng/buildpacks/kronos/
      #     docker build --load -t ${DOCKER_IMAGE_PREFIX:-ghcr.io/codbex/}kronos-buildpacks-stack-base . --target base
      #     docker push ${DOCKER_IMAGE_PREFIX:-ghcr.io/codbex/}kronos-buildpacks-stack-base
      #     docker build --load -t ${DOCKER_IMAGE_PREFIX:-ghcr.io/codbex/}kronos-buildpacks-stack-run . --target run
      #     docker push ${DOCKER_IMAGE_PREFIX:-ghcr.io/codbex/}kronos-buildpacks-stack-run
      #     docker build --load -t ${DOCKER_IMAGE_PREFIX:-ghcr.io/codbex/}kronos-buildpacks-stack-build . --target build
      #     docker push ${DOCKER_IMAGE_PREFIX:-ghcr.io/codbex/}kronos-buildpacks-stack-build
      #     cd buildpack/
      #     find *.toml -type f -exec sed -i ''s/#{KronosVersion}#/latest/g'' {} \;
      #     pack buildpack package ${DOCKER_IMAGE_PREFIX:-ghcr.io/codbex/}kronos-buildpacks --config ./package.toml
      #     docker push ${DOCKER_IMAGE_PREFIX:-ghcr.io/codbex/}kronos-buildpacks
      #     pack builder create ${DOCKER_IMAGE_PREFIX:-ghcr.io/codbex/}kronos-buildpacks-builder --config ./builder.toml
      #     docker push ${DOCKER_IMAGE_PREFIX:-ghcr.io/codbex/}kronos-buildpacks-builder
      #     cd ../../../../
      # - name: Kronos Kyma Buildpack
      #   run: |
      #     cd releng/buildpacks/kronos-kyma/
      #     docker build --load -t ${DOCKER_IMAGE_PREFIX:-ghcr.io/codbex/}kronos-buildpacks-stack-base-kyma . --target base
      #     docker push ${DOCKER_IMAGE_PREFIX:-ghcr.io/codbex/}kronos-buildpacks-stack-base-kyma
      #     docker build --load -t ${DOCKER_IMAGE_PREFIX:-ghcr.io/codbex/}kronos-buildpacks-stack-run-kyma . --target run
      #     docker push ${DOCKER_IMAGE_PREFIX:-ghcr.io/codbex/}kronos-buildpacks-stack-run-kyma
      #     docker build --load -t ${DOCKER_IMAGE_PREFIX:-ghcr.io/codbex/}kronos-buildpacks-stack-build-kyma . --target build
      #     docker push ${DOCKER_IMAGE_PREFIX:-ghcr.io/codbex/}kronos-buildpacks-stack-build-kyma
      #     cd buildpack/
      #     find *.toml -type f -exec sed -i ''s/#{KronosVersion}#/latest/g'' {} \;
      #     pack buildpack package ${DOCKER_IMAGE_PREFIX:-ghcr.io/codbex/}kronos-buildpacks-kyma --config ./package.toml
      #     docker push ${DOCKER_IMAGE_PREFIX:-ghcr.io/codbex/}kronos-buildpacks-kyma
      #     pack builder create ${DOCKER_IMAGE_PREFIX:-ghcr.io/codbex/}kronos-buildpacks-builder-kyma --config ./builder.toml
      #     docker push ${DOCKER_IMAGE_PREFIX:-ghcr.io/codbex/}kronos-buildpacks-builder-kyma
      #     cd ../../../../
      # - name: Kronos Kyma Runtime Buildpack
      #   run: |
      #     cd releng/buildpacks/kronos-kyma-runtime/
      #     docker build --load -t ${DOCKER_IMAGE_PREFIX:-ghcr.io/codbex/}kronos-buildpacks-stack-base-kyma-runtime . --target base
      #     docker push ${DOCKER_IMAGE_PREFIX:-ghcr.io/codbex/}kronos-buildpacks-stack-base-kyma-runtime
      #     docker build --load -t ${DOCKER_IMAGE_PREFIX:-ghcr.io/codbex/}kronos-buildpacks-stack-run-kyma-runtime . --target run
      #     docker push ${DOCKER_IMAGE_PREFIX:-ghcr.io/codbex/}kronos-buildpacks-stack-run-kyma-runtime
      #     docker build --load -t ${DOCKER_IMAGE_PREFIX:-ghcr.io/codbex/}kronos-buildpacks-stack-build-kyma-runtime . --target build
      #     docker push ${DOCKER_IMAGE_PREFIX:-ghcr.io/codbex/}kronos-buildpacks-stack-build-kyma-runtime
      #     cd buildpack/
      #     find *.toml -type f -exec sed -i ''s/#{KronosVersion}#/latest/g'' {} \;
      #     pack buildpack package ${DOCKER_IMAGE_PREFIX:-ghcr.io/codbex/}kronos-buildpacks-kyma-runtime --config ./package.toml
      #     docker push ${DOCKER_IMAGE_PREFIX:-ghcr.io/codbex/}kronos-buildpacks-kyma-runtime
      #     pack builder create ${DOCKER_IMAGE_PREFIX:-ghcr.io/codbex/}kronos-buildpacks-builder-kyma-runtime --config ./builder.toml
      #     docker push ${DOCKER_IMAGE_PREFIX:-ghcr.io/codbex/}kronos-buildpacks-builder-kyma-runtime
      #     cd ../../../../
      # - name: Kronos Cloud Foundry Buildpack
      #   run: |
      #     cd releng/buildpacks/kronos-cf/
      #     docker build --load -t ${DOCKER_IMAGE_PREFIX:-ghcr.io/codbex/}kronos-buildpacks-stack-base-cf . --target base
      #     docker push ${DOCKER_IMAGE_PREFIX:-ghcr.io/codbex/}kronos-buildpacks-stack-base-cf
      #     docker build --load -t ${DOCKER_IMAGE_PREFIX:-ghcr.io/codbex/}kronos-buildpacks-stack-run-cf . --target run
      #     docker push ${DOCKER_IMAGE_PREFIX:-ghcr.io/codbex/}kronos-buildpacks-stack-run-cf
      #     docker build --load -t ${DOCKER_IMAGE_PREFIX:-ghcr.io/codbex/}kronos-buildpacks-stack-build-cf . --target build
      #     docker push ${DOCKER_IMAGE_PREFIX:-ghcr.io/codbex/}kronos-buildpacks-stack-build-cf
      #     cd buildpack/
      #     find *.toml -type f -exec sed -i ''s/#{KronosVersion}#/latest/g'' {} \;
      #     pack buildpack package ${DOCKER_IMAGE_PREFIX:-ghcr.io/codbex/}kronos-buildpacks-cf --config ./package.toml
      #     docker push ${DOCKER_IMAGE_PREFIX:-ghcr.io/codbex/}kronos-buildpacks-cf
      #     pack builder create ${DOCKER_IMAGE_PREFIX:-ghcr.io/codbex/}kronos-buildpacks-builder-cf --config ./builder.toml
      #     docker push ${DOCKER_IMAGE_PREFIX:-ghcr.io/codbex/}kronos-buildpacks-builder-cf
      #     cd ../../../../
      - name: Slack Notification
        if: ${{ failure() && env.SLACK_WEBHOOK_URL != '' }}
        uses: slackapi/slack-github-action@v1.14.0
        with:
          payload: "{\"type\":\"Build\",\"url\":\"${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}\"}"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
